### ISSUE TITLE
installation does not work

### ISSUE THREAD

**Issue by Sanderand** [UXPin/uxpin-merge-boilerplate-proptypes#56]
I cloned the repo and tried to install dependencies with `npm i` and `yarn install`. both generate the same warnings and error. please help!

```
➜  uxpin-merge-boilerplate git:(master) yarn -v
1.22.18
➜  uxpin-merge-boilerplate git:(master) npm -v
8.3.1
➜  uxpin-merge-boilerplate git:(master) node -v
v16.14.0

...

2 warnings generated.
  rm -f Release/sass.a && ./gyp-mac-tool filter-libtool libtool  -static -o Release/sass.a Release/obj.target/libsass/src/libsass/src/ast.o Release/obj.target/libsass/src/libsass/src/ast_fwd_decl.o Release/obj.target/libsass/src/libsass/src/backtrace.o Release/obj.target/libsass/src/libsass/src/base64vlq.o Release/obj.target/libsass/src/libsass/src/bind.o Release/obj.target/libsass/src/libsass/src/cencode.o Release/obj.target/libsass/src/libsass/src/check_nesting.o Release/obj.target/libsass/src/libsass/src/color_maps.o Release/obj.target/libsass/src/libsass/src/constants.o Release/obj.target/libsass/src/libsass/src/context.o Release/obj.target/libsass/src/libsass/src/cssize.o Release/obj.target/libsass/src/libsass/src/emitter.o Release/obj.target/libsass/src/libsass/src/environment.o Release/obj.target/libsass/src/libsass/src/error_handling.o Release/obj.target/libsass/src/libsass/src/eval.o Release/obj.target/libsass/src/libsass/src/expand.o Release/obj.target/libsass/src/libsass/src/extend.o Release/obj.target/libsass/src/libsass/src/file.o Release/obj.target/libsass/src/libsass/src/functions.o Release/obj.target/libsass/src/libsass/src/inspect.o Release/obj.target/libsass/src/libsass/src/json.o Release/obj.target/libsass/src/libsass/src/lexer.o Release/obj.target/libsass/src/libsass/src/listize.o Release/obj.target/libsass/src/libsass/src/memory/SharedPtr.o Release/obj.target/libsass/src/libsass/src/node.o Release/obj.target/libsass/src/libsass/src/operators.o Release/obj.target/libsass/src/libsass/src/output.o Release/obj.target/libsass/src/libsass/src/parser.o Release/obj.target/libsass/src/libsass/src/plugins.o Release/obj.target/libsass/src/libsass/src/position.o Release/obj.target/libsass/src/libsass/src/prelexer.o Release/obj.target/libsass/src/libsass/src/remove_placeholders.o Release/obj.target/libsass/src/libsass/src/sass.o Release/obj.target/libsass/src/libsass/src/sass2scss.o Release/obj.target/libsass/src/libsass/src/sass_context.o Release/obj.target/libsass/src/libsass/src/sass_functions.o Release/obj.target/libsass/src/libsass/src/sass_util.o Release/obj.target/libsass/src/libsass/src/sass_values.o Release/obj.target/libsass/src/libsass/src/source_map.o Release/obj.target/libsass/src/libsass/src/subset_map.o Release/obj.target/libsass/src/libsass/src/to_c.o Release/obj.target/libsass/src/libsass/src/to_value.o Release/obj.target/libsass/src/libsass/src/units.o Release/obj.target/libsass/src/libsass/src/utf8_string.o Release/obj.target/libsass/src/libsass/src/util.o Release/obj.target/libsass/src/libsass/src/values.o
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/Users/sandeand/.node-gyp/16.14.0/include/node -I/Users/sandeand/.node-gyp/16.14.0/src -I/Users/sandeand/.node-gyp/16.14.0/deps/openssl/config -I/Users/sandeand/.node-gyp/16.14.0/deps/openssl/openssl/include -I/Users/sandeand/.node-gyp/16.14.0/deps/uv/include -I/Users/sandeand/.node-gyp/16.14.0/deps/zlib -I/Users/sandeand/.node-gyp/16.14.0/deps/v8/include -I../../nan -I../src/libsass/include  -O3 -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=c++11 -stdlib=libc++ -fno-rtti -fno-exceptions -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:58:
In file included from /Users/sandeand/.node-gyp/16.14.0/include/node/node.h:63:
In file included from /Users/sandeand/.node-gyp/16.14.0/include/node/v8.h:30:
/Users/sandeand/.node-gyp/16.14.0/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Darwin 20.6.0
gyp ERR! command "/Users/sandeand/.nvm/versions/node/v16.14.0/bin/node" "/Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/node-sass
gyp ERR! node -v v16.14.0
```

```
➜  uxpin-merge-boilerplate git:(master) npm start

> uxpin-merge-boilerplate@1.0.0 start
> uxpin-merge --disable-tunneling


You are using @uxpin/merge-cli version: 2.7.10

ERROR: Built at: 08/04/2022 12:02:18

ERROR in ./src/components/CreditCard/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/sass-loader/dist/cjs.js!./src/components/CreditCard/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (/Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at getDefaultSassImplementation (/Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
    at getSassImplementation (/Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
    at Object.loader (/Users/sandeand/Desktop/projects/workbench/@workbench/uxpin-merge-boilerplate/node_modules/sass-loader/dist/index.js:40:61)
 @ ./src/components/CreditCard/styles.scss 2:26-153
 @ ./src/components/CreditCard/CreditCard.jsx
 @ ./.uxpin-merge/components.js
```

**Comment by jackbehar** [comment]
Hi Andre - Thanks for reaching out. 

It appears that issue is with the version of node that you're using. Instead of using v16.14.0 can you use an earlier version, such as v12.18.1 up to v14.15.4

Node Version Manager might help to do so: https://github.com/nvm-sh/nvm

Please let us know if you need anything further.

Jack
